version: '2'
services:

  statusbot:
    environment:
      NODE_ENV: development
      TOKEN: ---
      STATUS_API_URL: ---
      BOTPORT: 1811
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: statusbot:local-latest
    ports:
      - 1811:1811
    volumes:
        - ./:/opt/
    command: nodemon
