version: '2'
services:

  statusbot:
    env_file:
      variables.env
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: statusbot:local-latest
    ports:
      - 1811:1811
    volumes:
        - ./:/opt/
    command: nodemon
